import { Inter, Lora } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SearchInput from "@/components/SearchInput";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "FilmDB",
  description: "Generated by Ezequiel Gómez de Lima",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <nav className="flex justify-around w-full bg-black h-14 text-white">
          <Link href="/">
            <img
              src="/cinesphere_logo.svg"
              className="pl-6 h-full w-auto"
            ></img>
          </Link>
          <SearchInput />
        </nav>
        {children}
        <footer className="w-full p-5 text-center bg-black h-14 text-white tabs">
          Created by{" "}
          <a
            href="https://github.com/ezequielgdl"
            className="hover:text-primary"
          >
            Ezequiel Gómez de Lima
          </a>{" "}
        </footer>
      </body>
    </html>
  );
}
